### PR TITLE
Add some love

### PR DESCRIPTION
**Pull request by Goutte**
Make second parameter optional,
sanitize directory configuration (to allow for `~` for example),
sort matches alphabetically,
fix git clone target directory,
and overall dustup.

---

On my (private) version, I also removed the `.py` extension from the file, to give it an executable feeling.

You can pull this or cherry-pick the good stuff (like the fix and sort) if you disagree on some of these changes, I don't care ; I'm happy. :)

Also, thank you ! :lollipop:

### CODE REVIEW

**Comment by janclarin** [comment]
Your changes make a lot of sense. In all honesty, I hacked up this script fairly quickly and haven't looked at it since. I like all of the changes you made and I will be incorporating them into this version.

Adding the shebang for python3 and allowing for just 2 arguments make so much sense, and I will be changing the instructions in the readme to match that.

Thank you so much, I will look into building off of the script in the future. If you have any further suggestions, please don't hesitate to let me know :smile:

**Comment by janclarin** [comment]
@Goutte If you're still using my crude python script to add material design icons to your apps, I recommend checking out this more fine-tuned IntelliJ/Android Studio plugin: https://plugins.jetbrains.com/plugin/7647?pr= that does it all within the IDE.

**Comment by Goutte** [comment]
Thanks for the tip !

I love that script, though ; I don't use it that often but each time I'm glad I have it ;)

**Comment by janclarin** [comment]
No problem! Glad you enjoy it :dancer:

**Pull request merged**
